with open('assets/css/style.css', 'a', encoding='utf-8') as f:
    f.write('\n\n/* Comprehensive RTL Fix for Floating Labels */\n')
    f.write('[dir="rtl"] .floating-label-group label {\n')
    f.write('  left: auto !important;\n')
    f.write('  right: 4px !important;\n')
    f.write('}\n')
    f.write('[dir="rtl"] .floating-label-group input,\n')
    f.write('[dir="rtl"] .floating-label-group select,\n')
    f.write('[dir="rtl"] .floating-label-group textarea {\n')
    f.write('  text-align: right !important;\n')
    f.write('}\n')
    f.write('[dir="rtl"] .floating-label-group select {\n')
    f.write('  padding-left: 30px !important;\n')
    f.write('  padding-right: 4px !important;\n')
    f.write('}\n')
